# Generated by Django 4.0 on 2022-01-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='Etat',
            field=models.CharField(choices=[('Libre', 'libre'), ('Occupé', 'Occupé')], default='Libre', max_length=50),
        ),
    ]
