# Generated by Django 4.0 on 2022-01-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_commande_commandes_date_debut_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandes',
            old_name='date_debut_location',
            new_name='date_commande',
        ),
        migrations.RemoveField(
            model_name='commandes',
            name='date_fin_location',
        ),
    ]
