# Generated by Django 4.0 on 2022-01-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_date_debut_location_commandes_date_commande_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maison',
            old_name='Prix_de_vente',
            new_name='Prix',
        ),
    ]
